name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run all test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm install
      - run: npm run build

  setup:
    name: Setup instance
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clean instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            if [[ -d ${{ secrets.APP_PATH }} ]]
            then
                cd ${{ secrets.APP_PATH }}
                git pull

            else
                mkdir ${{ secrets.APP_PATH }}
                cd ${{ secrets.APP_PATH }}

                git clone https://github.com/saraluzsas/ariella.git .
                echo "Please, setup the .env file and firebase keys on /repo folder"

            fi

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs:
      - test
      - setup
    steps:
      - name: Build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.APP_PATH }}

            # install and build

            npm install
            npm run build

            # load balancer

            npm i -g pm2

            if [ pm2 pid ${{ secrets.APP_PROCESS_NAME }} ]
            then
              pm2 restart ${{ secrets.APP_PROCESS_NAME }}
            
            else
              pm2 start dist/main.js --name ${{ secrets.APP_PROCESS_NAME }} --watch

            fi