name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run all test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm install
      - run: npm run build